name: Flyway Validate on DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flyway-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Flyway Validate
        uses: flyway/flyway-action@v2
        with:
          url: jdbc:sqlserver://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }};databaseName=${{ secrets.DB_NAME }}
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:flyway/sql
          command: validate