name: Flyway CI

on:
  push:
    branches:
      - main

jobs:
  flyway-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Flyway Validate on DEV
      uses: redgate/flyway-action@v2
      with:
        flyway-version: 11.14.1
        url: jdbc:sqlserver://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }};databaseName=${{ secrets.DB_NAME }}
        user: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASSWORD }}
        locations: filesystem:${{ github.workspace }}/flyway/sql
        command: validate
